### ISSUE TITLE
General questions about this project

### ISSUE THREAD

**Issue by amolari** [f5devcentral/application-study-tool#29]
Very interesting project, which I plan to soon implement in my lab.
A couple of questions:

1. do you plan to support NEXT ? The integreation should be even smoother as OTEL is native on NEXT.
2. What is F5 DataFabric? Could you provide an link in your README? I haven't found any information about it on AskF5 nor DC.

**Comment by clhain** [comment]
Added datafabric page in sites revamp: https://f5devcentral.github.io/application-study-tool/datafabric

Closing out under https://github.com/f5devcentral/application-study-tool/pull/33
