### ISSUE TITLE
Visual representation of the tool in the readme

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/application-study-tool#3]
Not a bug or RFE, but a documentation request.

Please add a couple of screen shots of what the tools looks like and the data it shows.  Possibly even a GIF of a quick 10 second walkthrough.

Just something to provide a visual of what tool is and does.

I use LICEcap to make GIFs.  https://www.cockos.com/licecap/

Example README:  https://github.com/f5devcentral/vscode-f5/blob/main/README.md

**Comment by clhain** [comment]
Good call Ben, tracking internally - will ping you the bug
