### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by grabera7** [f5devcentral/application-study-tool#44]
Custom Instance of OpenTelemetry Collector with enhanced BIG-IP data receivers (data fetched via iControlRest) [Full List of Metrics Collected](https://github.com/f5devcentral/application-study-tool/blob/main/pages/receiver_metrics.md).

The above link for collected metrics does not work from https://github.com/f5devcentral/application-study-tool/blob/main/README.md

**Comment by clhain** [comment]
This should be resolved, thanks for flagging
