### ISSUE TITLE
OTEL collector Error Code 400

### ISSUE THREAD

**Issue by 0xmonkey** [f5devcentral/application-study-tool#51]
**Describe the bug**

When running docker compose up, everything starts but the connection to our F5 fails with the error code: 

otel-collector-1  | 2024-11-07T21:37:04.178Z    error   scraperhelper/scrapercontroller.go:197  Error scraping metrics  {"kind": "receiver", "name": "bigip/1", "data_type": "metrics", "error": "endpoint /mgmt/tm/security/firewall/policy returned code 400; endpoint /mgmt/tm/security/nat/policy returned code 400", "scraper": "bigip"}
otel-collector-1  | go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
otel-collector-1  |     go.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:197
otel-collector-1  | go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
otel-collector-1  |     go.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:173
otel-collector-1  | 2024-11-07T21:37:04.179Z    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "debug/bigip", "resource metrics": 1, "metrics": 266, "data points": 19707}

**To Reproduce**
run command "docker compose up"

**Expected behavior**
i expect this to connect to our F5 and start pulling data
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS

**Additional context**
Add any other context about the problem here, including BigIP service account permission level, BigIP Versions.

**Attachments**
If the issue is in regards to missing data in dashboards, please also run the following from the installed host and attach the output:

```
curl 'localhost:9090/federate?match[]=%7B__name__%3D~"f5.%2A"%7D'
```

Logs for the collector can be gathered with:
```
docker logs application-study-tool-otel-collector-1 --tail 1000
```

**Comment by clhain** [comment]
Hi there, this is a result of how iControl Rest handles unconfigured/provisioned modules. As long as you don't have NAT and firewall policies enabled this is safe to ignore. We're evaluating how to strike the right balance between hiding these expected errors and inadvertently suppressing actual notifications about real problems. I'll go ahead and close this out but please reopen if needed.
