### ISSUE TITLE
Display data rates as megabits not megabytes

### ISSUE THREAD

**Issue by init4** [f5devcentral/application-study-tool#61]
The AST seems to use bytes per second everywhere it is describing a data rate. This is an unusual way of measuring throughput. The BIG-IP on-box graphs, and indeed the F5 licensing scheme will typically use bits per second. 

It is more common to use bits when describing throughput.

**Comment by mikempw** [comment]
Hey @init4 - We've had several people comment on the pro/con of doing this. I'll close the ticket and add this to the feedback.
