### ISSUE TITLE
Setting HTTPS and AD Authentication for Grafana

### ISSUE THREAD

**Issue by powerballad** [f5devcentral/application-study-tool#62]
I want to make access to AST use HTTPS and AD authentication.  If I follow the documentation on the Grafana website, it does not work.  I think maybe the config files Grafana is saying to update are not the same files used by the AST Grafana instance.  Please help.

**Comment by mikempw** [comment]
Just to clarify @powerballad is this AD or LDAP?

**Comment by powerballad** [comment]
Sorry, LDAP.

**Comment by clhain** [comment]
In either case, this is a stock Grafana docker image. We mount a couple of directories with datasource / dashboards, and set a few environment variables to configure it (see the .env file in your project root), but there's nothing beyond that which should conflict.

For simplicity, I'd suggest making it work with the instructions they provide here: https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#run-grafana-via-docker-compose

And then translate that over to the AST compose file, specifically this section:

https://github.com/f5devcentral/application-study-tool/blob/main/docker-compose.yaml#L42

If it still doesn't work, please provide the working configs from the stock instructions and I'll see if there's something else I'm not thinking of at the moment.

**Comment by clhain** [comment]
actually just noticed in step 2 they're using image: grafana/grafana-enterprise... make sure that's the OSS one: image: grafana/grafana:11.2.0, otherwise everything else should be the same.

**Comment by clhain** [comment]
closing for now, let me know if it looks like something specific with the ast grafana setup
