### ISSUE TITLE
Home Dashboards Device Virtual Servers - Scale update for VS CPU and VS ASM CPU

### ISSUE THREAD

**Issue by jackf242** [f5devcentral/application-study-tool#63]
**Describe the bug**
Chart scaling needs updated please under Device Virtual Servers.  This was noted during the lab development for the tool. 

**To Reproduce**

Need a BIGIP with a VS handling enough traffic to report CPU utilization viewed via: tmsh show ltm virtual X

Go to: [Home] > [Dashboards] > [BigIP - Device] > Device Virtual Servers

Review the Device Virtual Server CPU Chart and the ASM CPU Chart--the scale is incorrect.

Edit the Virtual Server CPU Utilization chart.
Under Standard Options correct the unit to: Percent (0-100), then change the Min to 1 and the Max to 100 to correct the scaling. 

Edit the Virtual Server ASM CPU Utilization chart.
Under standard Options correct the unit to: Percent (0.0-100)

**Screenshots**
Prior to my changes:
![image](https://github.com/user-attachments/assets/2c6754d7-1d31-4768-b599-4d8c704a5854)

![image](https://github.com/user-attachments/assets/fd09f9e4-b788-4235-94d0-d6ebd90ce0eb)

After I made the updates:

<img width="1622" alt="image" src="https://github.com/user-attachments/assets/ed229665-f0b4-4020-b296-1ec0cef70199">

**Desktop (please complete the following information):**
OSX FF

**Additional context**
Internal UDF environment available for repro

**Comment by jackf242** [comment]
This issue also appears on the Top N page.

**Comment by mikempw** [comment]
Thanks for the info! We will get that updated.

**Comment by clhain** [comment]
Fix in #64

**Comment by clhain** [comment]
Complete, v0.7.1
